### ISSUE TITLE
Generate VDR using Github Actions

### ISSUE THREAD

**Issue by Scanteianu** [adoptium/temurin-vdr-generator#7]
create a github action which generates the vdr and attaches it as a build artifact.

**Comment by smlambert** [comment]
Additional notes:
- This new GH action could 2 types of trigger to start with:
  - on a regular schedule via [schedule](https://docs.github.com/en/actions/using-workflows/events-that-trigger-workflows#schedule)
  - manually via [workflow_dispatch](https://docs.github.com/en/actions/using-workflows/events-that-trigger-workflows#workflow_dispatch)
